title: 'KOT3 — Kyoto 2026'
baseURL: 'https://y-susuki.github.io/kot3/'
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true
build:
  writeStats: true
enableGitInfo: false
enableRobotsTXT: true
enableEmoji: true
summaryLength: 30
pagination:
  pagerSize: 10
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
markup:
  _merge: deep
security:
  _merge: deep
