main:
  - name: About
    url: '#about'
    weight: 10
  - name: Speakers
    url: '#speakers'
    weight: 20
  - name: Program
    url: '#program'
    weight: 30
  - name: Committee
    url: '#committee'
    weight: 40
  - name: Access
    url: '#access'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
